framework:
    messenger:
        default_bus: default.bus
        buses:
            default.bus: ~
            query.bus: ~
            command.bus:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_transaction
            event.bus:
                default_middleware:
                    allow_no_handlers: true

when@test:
    framework:
        messenger:
            transports:
                event.bus: 'test://'
            routing:
                'Trade\Domain\Event\DomainEventInterface': event.bus
