nelmio_api_doc:
    documentation:
        info:
            title: API сервиса торгов за перевозку
            description: Документация к API сервиса торгов за перевозку
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
            parameters:
                offsetParam:
                    name: 'offset'
                    in: 'query'
                    required: true
                    schema:
                        type: integer
                        format: int32
                        minimum: 0
                        default: 0
                limitParam:
                    name: 'limit'
                    in: 'query'
                    required: true
                    schema:
                        type: integer
                        format: int32
                        minimum: 1
                        maximum: 100
                        default: 100
        security:
            -   Bearer: [ ]

        paths:
            /api/doc.json:
                get:
                    summary: Документация в формате JSON.
                    tags: [ Документация ]
                    requestBody:
                        content:
                            application/json:

    areas:
        path_patterns:
            - ^/api(?!/doc$)
